<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function remove($id){

        $this
                ->createQueryBuilder('task')
                ->delete()
                ->where('task.id = :id')
                ->setParameter('id', $id)
                ->getQuery()
                ->getResult();
        return;
    }
}
